/*
Stefan Pleava
Humberview SS
07/05/2014
ICS4UO
Sorting Project
A program that showcases the various sorting algorithms with various data types and different amounts of data 
*/
package finalProject;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Stefan
 */
public class searchBonus extends javax.swing.JFrame {

    /**
     * Creates new form searchBonus
     */
    // inits some variables
    public static int[] bigArray;
    public static int search=0;

    public searchBonus() {
        //inits all the gui components made by the plugin
        initComponents();
        //sets the icon and title for the window
        this.setIconImage(new ImageIcon(getClass().getResource("sort.png")).getImage());
        this.setTitle("The Sorting Visualizer");
    }

    public void fillArray(int amount) {
        //fills an array with randomly generated data
        bigArray = new int[amount];
        for (int x = 0; x < bigArray.length; x++) {
            bigArray[x] = (int) ((Math.random() * 90) + 1);
            arrayText.append(""+bigArray[x]+", ");
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        searchText = new javax.swing.JTextField();
        searchLabel = new javax.swing.JLabel();
        goButton = new javax.swing.JButton();
        arrayLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arrayText = new javax.swing.JTextArea();
        placeInArrayLabel = new javax.swing.JLabel();
        placeInArrayText = new javax.swing.JTextField();
        generateButton = new javax.swing.JButton();
        guessLabel = new javax.swing.JLabel();
        guessText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        title.setText("Search Game (1-99)");

        searchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextActionPerformed(evt);
            }
        });

        searchLabel.setText("Search:");

        goButton.setText("Go");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        arrayLabel.setText("Array");

        arrayText.setColumns(20);
        arrayText.setLineWrap(true);
        arrayText.setRows(5);
        arrayText.setText("Generate an array    and then guess the  position of numbers in it. Search for   numbers by typing   them and pressing  the go button.");
        jScrollPane1.setViewportView(arrayText);

        placeInArrayLabel.setText("Place In Array");

        placeInArrayText.setEnabled(false);
        placeInArrayText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeInArrayTextActionPerformed(evt);
            }
        });

        generateButton.setText("Generate");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        guessLabel.setText("Number Guess");

        guessText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchText, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(searchLabel, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(placeInArrayLabel, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(placeInArrayText, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(arrayLabel, javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                                .addComponent(generateButton)
                                .addGap(0, 0, 0)
                                .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(guessLabel)
                                .addComponent(guessText, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(18, 18, 18)
                .addComponent(arrayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(guessLabel)
                .addGap(4, 4, 4)
                .addComponent(guessText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(placeInArrayLabel)
                .addGap(4, 4, 4)
                .addComponent(placeInArrayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goButton)
                    .addComponent(generateButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        // TODO add your handling code here:
        //sets all the gui text to certain things as well as gets texts from certain text bocrd
        arrayText.setText("");
        placeInArrayText.setText("");
        search = Integer.parseInt(searchText.getText());
        searchArray(Integer.parseInt(guessText.getText()));
    }//GEN-LAST:event_goButtonActionPerformed

    private void placeInArrayTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeInArrayTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placeInArrayTextActionPerformed

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        // TODO add your handling code here:
        //fills an array with 99 values of random data
        fillArray(99);     
    }//GEN-LAST:event_generateButtonActionPerformed

    private void guessTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guessTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchBonus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchBonus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchBonus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchBonus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        // Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchBonus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrayLabel;
    private javax.swing.JTextArea arrayText;
    private javax.swing.JButton generateButton;
    private javax.swing.JButton goButton;
    private javax.swing.JLabel guessLabel;
    private javax.swing.JTextField guessText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel placeInArrayLabel;
    private javax.swing.JTextField placeInArrayText;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTextField searchText;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    public void searchArray(int t) {
    //shows a window if you guessed the right now
        // does a linear search through the entire array for a certain number
        for (int x = 0; x < bigArray.length; x++) {
            if (bigArray[x] == search) {
                placeInArrayText.setText(placeInArrayText.getText() + "" + x + ", ");
            if (t==x){
                JOptionPane.showMessageDialog(null, "Win!");
                break;
            }
            }
        }
    }
}
